//
// Created by radek on 05.12.2019.
//

/* Gramatyka terminala:
 *
 * STATEMENT = PIPE_CMD_CALL, [REDIRECTION], [STATEMENT_SEPARATOR, STATEMENT]
 *
 * PIPE_CMD_CALL = CMD_CALL, [PIPE_SEPARATOR, PIPE_CMD_CALL]
 *
 * CMD_CALL = CMD, [ARGS], [HERE_DOCUMENT]
 *
 * CMD = WORD | INTERNAL_COMMAND
 *
 * ARGS = VALUE, [ARGS]
 *
 * HERE_DOCUMENT = HD_MARKER, HD_TOKEN, NEWLINE, [HD_CONTENT], NEWLINE, HD_TOKEN
 *
 * VALUE = LITERAL | VAR_VALUE
 *
 * LITERAL = NUMBER | WORD | QUOTED_STRING
 *
 * QUOTED_STRING = APOSTROPHE, STRING, APOSTROPHE
 *
 * REDIRECTION = (REDIRECT_LEFT | REDIRECT_RIGHT) TARGET
 *
 * VAR_DEF = [EXPORT_KW], VAR_NAME, ASSIGN_OPERATOR, VALUE
 *
 * VAR VALUE = VALUE_EXTRACTOR, VAR_NAME
 *
 * PIPE_SEPARATOR = "|"
 * REDIRECT_LEFT = "<"
 * REDIRECT_RIGHT = ">"
 * ASSIGN_OPERATOR = "="
 * VALUE_EXTRACTOR = "$"
 * EXPORT_KW = "export"
 * INTERNAL_COMMAND = "cd" | "pwd" | "echo" | "exit"
 * STATEMENT_SEPARATOR = ";"
 * APOSTROPHE = "'"
 * NEWLINE = "\n"
 * HD_MARKER = "<<"
 * STRING = .+
 * WORD = \w+
 * NUMBER = \d+
 * VAR_NAME = [a-zA-Z_]\w*
 */

#include "Parser.h"
